nodeLinker: node-modules
progressBarStyle: 'patrick'
npmRegistryServer: https://registry.npmmirror.com
npmScopes:
  tastien:
    npmRegistryServer: http://npm.tastientech.com
unsafeHttpWhitelist:
  - npm.tastientech.com
logFilters:
  - code: 'YN0002'
    level: discard

yarnPath: .yarn/releases/yarn-3.6.4.cjs
