export enum BatchOperation {
  selectedText = '已选',
  totalFolder = '个文件夹,共',
  totalPoint = '个资源',
  confirmText = '确定',
  cancelText = '取消',
  emptyTip = '请选择分组或点位',
  moveText = '移动',
  movingTip = '正在移动中',
  moveSuccess = '移动成功',
  moveFailure = '无权限操作',
  batchEdit = '批量编辑',
  deleteText = '删除',
  continueDelete = '继续删除',
  deleteSuccess = '删除成功',
  deleteFail = '无权限操作',
  deleteSelected = '删除所选内容',
  deleteNotRevert = '删除后无法恢复，请谨慎操作',
  deleteWithFolder = '同时删除文件夹',
  signRangeExceeds = '不在可打卡范围内，请在靠近一点',
}

export enum GroupManage {
  createText = '创建',
  updatingTip = '正在更新中',
  sortByUpdateTime = '按更新时间排序',
  selectText = '选择',
  selectAllText = '全选',
  selectInverseText = '取消全选',
  completeText = '完成',
  loadingTip = '正在加载中',
  addFolder = '添加分组',
  dealWithPointer = '请处理已选点位',
  viewMapText = '查看地图',
  modifingTip = '正在修改中',
  modifySuccessTip = '修改成功',
  circleSelection = '圈选选择',
  mapSelection = '地图选择',
  returnClearTip = '返回后选中内容将不再保留',
  reDrawText = '重画',
  returnDinMapCollect = '是否退出钉图采集',
  confirmDispatch = '是否确认转派？',
}
